name: Executive Order Tracker

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/executive_order_tracker.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies manually (without requirements.txt)
      - name: Install dependencies
        run: |
          pip install --prefer-binary requests beautifulsoup4 transformers "torch>=2.0.0" flax "numpy<2"

      # Run the executive order tracker script
      - name: Run tracker script
        run: python executive_order_checker.py
