name: Executive Order Tracker

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies including PyTorch, TensorFlow, and Flax
      - name: Install dependencies
        run: |
          pip install torch==1.9.0  # Install PyTorch
          pip install tensorflow==2.0  # Install TensorFlow
          pip install flax  # Install Flax

      # Run the executive order tracker script
      - name: Run tracker script
        run: python executive_order_checker.py
