name: Executive Order Tracker

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies including PyTorch, TensorFlow, and Flax
      - name: Install dependencies
        run: |
          pip install requests  # Ensure requests is installed          
          pip install torch>=2.0.0  # Install the latest version of PyTorch 2.x
          pip install "numpy<2"  # Force downgrade to NumPy 1.x
          pip install flax  # Install Flax
          pip install beautifulsoup4  # Ensure beautifulsoup4 is installed
          pip install transformers


      # Run the executive order tracker script
      - name: Run tracker script
        run: python executive_order_checker.py
